version: "3.8"
services:
  mysql:
    container_name: ex_mysql
    image: mysql:latest
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file: ./db/.env
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: ex_redis
    hostname: ex_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
