spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spharos_test
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 1000
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always